-----------------------------------------------------댓글 시퀀스 추가

--댓글 시퀀스 생성 --
DROP SEQUENCE SEQ_REPLY;
CREATE SEQUENCE SEQ_REPLY_NO MINVALUE 1 NOCYCLE NOCACHE;
--SEQ_REPLY_NO.NEXTVAL;

--------------------------------------------------- 댓글 더미 데이터 바꾸기 
--REPLY(댓글)
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM,  CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, 1, '나는 더미데이터 댓글입니다 1', TIMESTAMP '2023-11-29 12:01:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM,  CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 2, 2, '나는 더미데이터 댓글입니다 2', TIMESTAMP '2023-11-29 12:02:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM, CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 3, 3, '나는 더미데이터 댓글입니다 3', TIMESTAMP '2023-11-29 12:03:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM,  CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 4, 4, '나는 더미데이터 댓글입니다 4', TIMESTAMP '2023-11-29 12:04:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM,  CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 5, 5, '나는 더미데이터 댓글입니다 5', TIMESTAMP '2023-11-29 12:05:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM,  CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 6, 6, '나는 더미데이터 댓글입니다 6', TIMESTAMP '2023-11-29 12:06:00', TIMESTAMP '2023-11-29 12:01:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM, CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 7, 7, '나는 더미데이터 댓글입니다 7', TIMESTAMP '2023-11-29 12:07:00', TIMESTAMP '2023-12-29 12:10:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM, CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 8, 8, '나는 더미데이터 댓글입니다 1', TIMESTAMP '2023-11-29 12:08:00', TIMESTAMP '2023-12-29 12:10:00',  'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM, CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL, 9, 9, '나는 더미데이터 댓글입니다 9', TIMESTAMP '2023-11-29 12:09:00',  TIMESTAMP '2023-12-29 12:10:00', 'N');
INSERT INTO REPLY (REPLY_NO, POST_NO, REPLY_MEM, CON, WRITE_DATE, UPDATE_DATE, DEL_YN) VALUES(SEQ_REPLY_NO.NEXTVAL,10, 10, '나는 더미데이터 댓글입니다 10', TIMESTAMP '2023-11-29 12:10:00',  TIMESTAMP '2023-12-29 12:10:00', 'N');
COMMIT;

-----------------------------------------------------고객센터 테이블 CHAR 값 변경 + DEL_YN 기본값 변경
DROP TABLE CUSTOMER_CENTER CASCADE CONSTRAINTS;  
CREATE TABLE CUSTOMER_CENTER (
   Q_NO               NUMBER          PRIMARY KEY
   ,ADMIN_NO           NUMBER
   ,MEM_NO               NUMBER
   ,Q_TIT               VARCHAR2(100)
   ,Q_CON               VARCHAR2(2000)
   ,Q_WRITE_DATE       TIMESTAMP       DEFAULT SYSDATE
   ,ANSEWR               VARCHAR2(4000)
   ,ANSEWR_DATE       TIMESTAMP
   ,UPDATE_DATE       TIMESTAMP
   ,DEL_YN               CHAR(1)           DEFAULT 'Y'
   ,QUESTION_CATEGORY   CHAR(2)          NOT NULL
);

--------------------------------------------------------공지사항 INSET 더미 데이터 수정 
--NOTICE (공지사항)
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 기타 테스트 입니다.','기타 테스트입니다.');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 기타 테스트 입니다.','기타 테스트입니다.');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 기타 테스트 입니다.','기타 테스트입니다.');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,FIXED_YN) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 고정 테스트 입니다.','고정 테스트입니다.','Y');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,FIXED_YN) VALUES (SEQ_NOTICE.NEXTVAL,'1','공지사항 고정 테스트 입니다.','고정 테스트입니다.','Y');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 기타 테스트 입니다.','기타 테스트입니다.');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 기타 테스트 입니다.','기타 테스트입니다.');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,DEL_YN) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 비공개 테스트 입니다.','비공개 테스트입니다.','N');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,FIXED_YN,DEL_YN) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 비공개 테스트 입니다.','비공개 테스트입니다.','Y','N');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,FIXED_YN,DEL_YN) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 비공개 테스트 입니다.','비공개 테스트입니다.','N','N');
INSERT INTO NOTICE(NOTICE_NO,ADMIN_NO,TITLE,CONTENT,FIXED_YN) VALUES (SEQ_NOTICE.NEXTVAL,'6','공지사항 고정 테스트 입니다.','고정 테스트입니다.','Y');
commit;