--admin 더미
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin','0000' );


INSERT INTO 
VOTE_BOARD
(
    VOTE_NO
    ,MANAGER_NO
    ,TITLE
    ,CONTENT
)
VALUES 
(
    SEQ_VOTE_BOARD_NO.NEXTVAL
    ,1
    ,'01번 테스트 전자 투표'
    ,'테스트용 투표 진행합니다.'
);
INSERT INTO 
VOTE_ITEM
(
    ITEM_NO
    ,VOTE_NO
    ,ITEM_NAME
    ,VOTE_ORDER
    ,VOTE_TYPE
)
VALUES
(
    SEQ_VOTE_ITEM_NO.NEXTVAL
    ,1
    ,'TEST1'
    ,1
    ,'일반투표'
);
INSERT INTO 
VOTE_ITEM
(
    ITEM_NO
    ,VOTE_NO
    ,ITEM_NAME
    ,VOTE_ORDER
    ,VOTE_TYPE
)
VALUES
(
    SEQ_VOTE_ITEM_NO.NEXTVAL
    ,1
    ,'TEST2'
    ,2
    ,'일반투표'
);
INSERT INTO 
VOTE_ITEM
(
    ITEM_NO
    ,VOTE_NO
    ,ITEM_NAME
    ,VOTE_ORDER
    ,VOTE_TYPE
)
VALUES
(
    SEQ_VOTE_ITEM_NO.NEXTVAL
    ,1
    ,'TEST3'
    ,3
    ,'일반투표'
);

INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,1,'2023-12-11 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,2,'2023-12-11 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,3,'2023-12-11 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,4,'2023-12-11 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,5,'2023-12-11 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,6,'2023-12-11 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,7,'2023-12-11 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,8,'2023-12-11 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,9,'2023-12-11 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,3,10,'2023-12-11 15:30:07');
COMMIT;