--admin 더미
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin','0000' );
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin01','0000' );


--VOTE 게시글, VOTE 항목, 
INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'01번 테스트 전자 투표1111' ,'1111 테스트용 투표 진행합니다.' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'찬성' ,1 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'반대' ,2 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'중립' ,3 ,'대규모투표' );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,1,'2023-12-11 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,2,'2023-12-11 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,3,'2023-12-11 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,4,'2023-12-11 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,5,'2023-12-11 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,6,'2023-12-11 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,7,'2023-12-11 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,8,'2023-12-11 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,9,'2023-12-11 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,3,10,'2023-12-11 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'02번 테스트 전자 투표2222' ,'2222 테스트용 투표 진행합니다.' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,2 ,'YES' ,1 ,'대규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,2 ,'NO' ,2 ,'대규모투표' );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,10,'2023-12-15 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT ,DEADLINE_DATE) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'03번 테스트 전자 투표2222' ,'3333 테스트용 투표 진행합니다.' ,'2023-12-30 15:30:58');
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'보라색' ,1 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'파란색' ,2 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'노란색' ,3 ,'소규모투표' );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,6,5,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,8,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,8,10,'2023-12-15 15:30:07');
INSERT INTO VOTE_HISTORY ( VOTE_HISTORY_NO ,VOTE_NO ,VOTE_NAME ,VOTE_COUNT ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_HISTORY_NO.NEXTVAL ,3 ,'파란색' ,3 ,2 );


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'04번 테스트 전자 투표2222' ,'4444 테스트용 투표 진행합니다.' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,4 ,'찬' ,1 ,'대규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,4 ,'반' ,2 ,'대규모투표' );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,10,'2023-12-15 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'05번 테스트 전자 투표2222' ,'5555 테스트용 투표 진행합니다.' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'김씨' ,1 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'이씨' ,2 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'박씨' ,3 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'정씨' ,4 ,'소규모투표' );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ,VOTE_TYPE ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'조씨' ,5 ,'소규모투표' );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,11,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,10,'2023-12-15 15:30:07');
--COMMIT;



