--관리자 
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'관리자01',1234);   
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'관리자02',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'관리자03',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin01',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin02',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'admin03',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'ADMIN01',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'ADMIN02',1234);
INSERT INTO MANAGER (MANAGER_NO,ID,PWD) VALUES (SEQ_MANAGER_NO.NEXTVAL,'ADMIN03',1234);

--세대 정보 
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 101, 101 , 10, 6000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 101, 201 , 20, 5000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 101, 301 , 20, 1000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 101, 401 , 30, 1000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 101, 501 , 40, 1000); -- 5번

INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 102, 101 , 10, 3000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 102, 201 , 20, 4000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 102, 301 , 30, 5000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 102, 401 , 40, 4000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 102, 501 , 50, 6000); -- 10번

INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 103, 101 , 60, 1000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 103, 201 , 40, 1000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 103, 301 , 10, 2000);
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 103, 401 , 10, 3453); 
INSERT INTO UNIT (UNIT_NO, DONG, HO, SCALE, VEH_TIME) VALUES (SEQ_UNIT_NO.NEXTVAL, 103, 501 , 10, 3453); -- 15번

--회원
INSERT INTO MEMBER (MEMBER_NO, UNIT_NO, PHONE, PWD, NAME, GENDER, BIRTH, PERMISSION_YN, JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, 1, '010-1111-1111', 'rlagmltjd12!A', '김지영', 'F', '201010', 'Y', TO_TIMESTAMP('2022-10-10 10:20:00', 'YYYY-MM-DD HH24:MI:SS'),'kh123@gmail.com','N');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,1,'010-2222-2222','rlagmltjd12!A','이승우','M','841010','Y','2023:01:02','kh123@gmail.com','N');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,1,'010-3333-3333','rlagmltjd12!A','박지원','M','861210','Y','2024:01:02 10:20:00','kh456@naver.com','Y');

INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,2,'010-4444-4444','rlagmltjd12!A','김수윤 ','F','861210','N','2024:01:02 10:20:00','kh1234@gmail.com' ,'Y');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,2,'010-5555-5555','rlagmltjd12!A','강혀빈 ','F','861210','N','2024:01:02 10:20:00','kh4567@gmail.com','N');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,2,'010-6666-6666','rlagmltjd12!A','송하영 ','F','861210','N','2024:01:02 10:20:00','kh1234@gmail.com','N');

INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,3,'010-7777-7777','rlagmltjd12!A','문태일  ','M','861210','Y','2024:01:02 10:20:00','kh7777@gmail.com','Y');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,3,'010-8888-8888','rlagmltjd12!A','서영호  ','M','861210','Y','2024:01:02 10:20:00','kh8888@gmail.com','N');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,3,'010-9999-9999','rlagmltjd12!A','이태용  ','M','861210','Y','2024:01:02 10:20:00','kh9999@gmail.com','N');
INSERT INTO MEMBER (MEMBER_NO,UNIT_NO,PHONE,PWD,NAME,GENDER,BIRTH,permission_yn,JOIN_DATE,EMAIL,OWNER_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL,3,'010-9999-9999','rlagmltjd12!A','이태용  ','M','861210','Y','2024:01:02 10:20:00','kh9999@gmail.com','N');

--방문주차
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,1,'그냥왔다','가나바1234','2024-01-03 02:33','2024-01-03 07:33', '2024-01-01 01');
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,2,'친구 보러 왔다','가나바1234','2024-01-03 02:33','2024-01-04 07:34', '2024-01-02 01');
INSERT INTO parking (PARKING_NO,MEMBE_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,3,'줄꺼 있어서 왔다','가나바1234','2024-01-03 02:33','2024-01-03 17:33', '2024-01-01 01');
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,4,'밥먹으러 왔다','가나바1234','2024-01-03 02:33','2024-01-03 02:33', '2024-01-02 01');

INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,1,'장보고 왔다','가나바1234','2024-01-03 02:33','2024-01-03 02:33','2024-01-02 01');
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ARRIVAL_TIME,DEPARTURE_TIME,ENROLL_DATE) VALUES (seq_parking_no.nextval,2,'드라마보러 왔다','가나바1234','2024-01-03 02:33','2024-01-03 02:33','2024-01-02 01');

INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE) VALUES (seq_parking_no.nextval,1,'잠시 왔다','가나바1234',SYSDATE);
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE) VALUES (seq_parking_no.nextval,2,'자고가려 왔다','가나바1234',SYSDATE);

INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,DEL_YN) VALUES (seq_parking_no.nextval,1,'엄마보러 왔다','가나바1234',SYSDATE,'Y');
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,DEL_YN) VALUES (seq_parking_no.nextval,2,'형보러 왔다','가나바1234',SYSDATE,'Y');

INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,DEL_YN,MODIFY_DATE) VALUES (seq_parking_no.nextval,1,'누나보러 왔다','가나바1234','2024-01-01','Y','2024-01-02' );
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,DEL_YN,MODIFY_DATE) VALUES (seq_parking_no.nextval,2,'할머니보러 왔다','가나바1234','2024-01-01','Y','2024-01-02');

INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,MODIFY_DATE) VALUES (seq_parking_no.nextval,1,'다시 왔다','가나바1234','2024-01-01', '2024-01-02' );
INSERT INTO parking (PARKING_NO,MEMBER_NO,PURPOSE,CAR_NO,ENROLL_DATE,MODIFY_DATE) VALUES (seq_parking_no.nextval,2,'내가 돌아왔다','가나바1234','2024-01-01','2024-01-02' );

-------------------------------공지사항
--공지사항 작성 
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 공사 단수 예정','제목이 아침부터 저녁까지 단순 예정입니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 엘리베이터 공사예정','수요일부터 금요일까지 공사 예정입니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 미끄럼 사고 주의','날씨가 추워 길이 얼었으니 조심하시길 바랍니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 배고픔 예정 단수 예정','제목이 아침부터 저녁까지 단순 예정입니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 엘리베이터 공사예정','수요일부터 금요일까지 공사 예정입니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO,MANAGER_NO,TITLE,CONTENT ) VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL,1,' 미끄럼 사고 주의','날씨가 추워 길이 얼었으니 조심하시길 바랍니다' );
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '주차장 이용 안내', '주차장 이용 시 주의사항을 숙지해주세요.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '시설물 점검 안내', '다음 주에 시설물 점검이 예정되어 있습니다. 이용에 참고해주세요.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '화재 예방 안내', '화재 예방을 위해 가스 밸브 확인 및 소화기 점검을 실시하오니 주민 여러분의 협조 부탁드립니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '휴게실 이용 안내', '휴게실은 주민들만 이용할수 있습니다');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '주민 회의 일정 안내', '다음 주 토요일에 주민 회의가 예정되어 있습니다. 참석 부탁드립니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '수도관 보수 작업 안내', '다음 달 초에 수도관 보수 작업이 진행될 예정입니다. 이용에 불편을 드려 죄송합니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '공동 협력사 모집', '주민 여러분 중에서 공동으로 협력할 수 있는 분들을 모집합니다. 관심 있는 분들은 문의 바랍니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '음주 운전 방지 캠페인', '음주 후 차량 운전은 위험합니다. 모두 함께 안전한 동네를 만들어갑시다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '주민 투표 안내', '주민 여러분께서 참여할 수 있는 주민 투표가 시작되었습니다. 의견을 나눠주세요.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '동네 공원 새로운 시설 투표', '동네 공원에 새로운 시설을 설치할 계획입니다. 주민 여러분의 투표를 기다립니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '주변 도로 개선 투표', '도로 개선 사업에 대한 주민 여러분의 의견을 듣고 있습니다. 투표에 참여해주세요.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '공동 시설 이용 규칙 변경 투표', '공동 시설 이용 규칙에 대한 변경 사항이 있습니다. 주민 투표에 참여해주시기 바랍니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, MANAGER_NO, TITLE, CONTENT)VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, 1, '동네 안전 캠페인 참여 의견 투표','동네 안전 캠페인 참여의견 투표가 있습니다');

-- TODO 사진 제대로 넣기~
--공지사항 파일
INSERT INTO ANNOUNCEMENT_IMG (IMG_NO,ANNOUNCEMENT_NO,IMG_NAME,PATH,ORIGIN_NAME) VALUES (SEQ_ANNOUNCEMENT_IMG_NO.NEXTVAL,1,'app/img','경로입니다','진짜이름입니다');
INSERT INTO ANNOUNCEMENT_IMG (IMG_NO,ANNOUNCEMENT_NO,IMG_NAME,PATH,ORIGIN_NAME) VALUES (SEQ_ANNOUNCEMENT_IMG_NO.NEXTVAL,1,'app/img','경로입니다','진짜이름입니다1');
INSERT INTO ANNOUNCEMENT_IMG (IMG_NO,ANNOUNCEMENT_NO,IMG_NAME,PATH,ORIGIN_NAME) VALUES (SEQ_ANNOUNCEMENT_IMG_NO.NEXTVAL,1,'app/img','경로입니다','진짜이름입니다2');
INSERT INTO ANNOUNCEMENT_IMG (IMG_NO,ANNOUNCEMENT_NO,IMG_NAME,PATH,ORIGIN_NAME) VALUES (SEQ_ANNOUNCEMENT_IMG_NO.NEXTVAL,2,'app/img','경로입니다','진짜이름입니다2');

-- 여기부터 민경님

--관리비 청구
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-12-03'
    , 100000
    , 100000
    , 10000
    , 210000
);
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-11-03'
    , 100000
    , 150000
    , 10000
    , 260000
);
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-10-03'
    , 100000
    , 110000
    , 10000
    , 220000
);

--커뮤니티시설 등록
INSERT INTO FACILITIES(
    FACILITIES_NO
    , FACILITIES_NAME
    , UNIT_PRICE
    , LOCATION
    , OPERATION_TIME
    , DAY_OFF
    , CONTACT
    , AMENITY
    , IMAGE
    , ENROLL_DATE
) VALUES (
    SEQ_FACILITIES_NO.NEXTVAL
    , '사우나'
    , 3000
    , '커뮤니티센터 1층'
    , '화~금 6:00~21:00, 토,일 9:00~18:00'
    , '월요일, 법정공휴일'
    , '0212345555'
    , '드라이기, 정수기'
    , 'http://127.0.0.1:8888/app\resources\upload\facility\사우나01.jpg'
    , '2023-12-01'
);
INSERT INTO FACILITIES(
    FACILITIES_NO
    , FACILITIES_NAME
    , UNIT_PRICE
    , LOCATION
    , OPERATION_TIME
    , DAY_OFF
    , CONTACT
    , AMENITY
    , IMAGE
    , ENROLL_DATE
) VALUES (
    SEQ_FACILITIES_NO.NEXTVAL
    , '체육관'
    , 1000
    , '커뮤니티센터 2층'
    , '화~금 6:00~21:00, 토,일 9:00~18:00'
    , '월요일, 법정공휴일'
    , '0212345555'
    , '정수기'
    , 'http://127.0.0.1:8888/app\resources\upload\facility\체육관01.jpg'
    , '2023-12-02'
);

--커뮤니티공지 등록 (관리자)
INSERT INTO FACILITIES_NOTICE(
    FACILITIES_NOTICE_NO
    , FACILITIES_NO
    , MANAGER_NO
    , TITLE
    , CONTENT
    , FILE_NAME
    , FILE_NAME_RAW
    , ENROLL_DATE
) VALUES (
    SEQ_FACILITIES_NOTICE.NEXTVAL
    , 1
    , 1
    , '제목'
    , '내용'
    , '변경이름'
    , '원본이름'
    , '2023-12-01'
);

INSERT INTO FACILITIES_NOTICE(
    FACILITIES_NOTICE_NO
    , FACILITIES_NO
    , MANAGER_NO
    , TITLE
    , CONTENT
    , FILE_NAME
    , FILE_NAME_RAW
    , ENROLL_DATE
) VALUES (
    SEQ_FACILITIES_NOTICE.NEXTVAL
    , 2
    , 1
    , '제목'
    , '내용'
    , '변경이름'
    , '원본이름'
    , '2023-12-02'
);


--예약추가(회원번호, 이용일)  
INSERT INTO FACILITIES_HISTORY(
    APPLICATION_NO
    , FACILITIES_NO
    , MEMBER_NO
    , USE_DATE
    , PRICE
    , APPLICATION_DATE
) VALUES (
    SEQ_FACILITIES_HISTORY_NO.NEXTVAL
    , 1
    , 1
    , '2023-12-01'
    , 3000
    , '2023-12-03'
);
INSERT INTO FACILITIES_HISTORY(
    APPLICATION_NO
    , FACILITIES_NO
    , MEMBER_NO
    , USE_DATE
    , PRICE
    , APPLICATION_DATE
) VALUES (
    SEQ_FACILITIES_HISTORY_NO.NEXTVAL
    , 1
    , 1
    , '2024-02-05'
    , 3000
    , '2023-12-03'
);



--관리비 추가
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-12-03'
    , 100000
    , 100000
    , 10000
    , 210000
);
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-11-03'
    , 100000
    , 150000
    , 10000
    , 260000
);
INSERT INTO MANAGEMENT_FEE(
    BILLING_NO
    , UNIT_NO
    , USAGE_PERIOD
    , BASIC_FEE
    , MAINTERNANCE_FEE
    , FACILITIES_FEE
    , TOTAL_AMOUNT
) VALUES (
    SEQ_MANAGEMENT_FEE_NO.NEXTVAL
    , 1
    , '2023-10-03'
    , 100000
    , 110000
    , 10000
    , 220000
);


-------------------------------------------------------입주민게시판
--카테고리 추가
INSERT INTO CATEGORY(
    CATEGORY_NO
    , CATEGORY_NAME
) VALUES (
    SEQ_CATEGORY_NO.NEXTVAL
    , '정보공유'
);
INSERT INTO CATEGORY(
    CATEGORY_NO
    , CATEGORY_NAME
) VALUES (
    SEQ_CATEGORY_NO.NEXTVAL
    , '문의'
);
INSERT INTO CATEGORY(
    CATEGORY_NO
    , CATEGORY_NAME
) VALUES (
    SEQ_CATEGORY_NO.NEXTVAL
    , '자유게시판'
);

--게시글 작성
INSERT INTO RESIDENT_BOARD(
    BOARD_NO
    , WRITER_NO
    , CATEGORY_NO
    , TITLE
    , CONTENT
    , ENROLL_DATE
) VALUES (
    SEQ_RESIDENT_BOARD_NO.NEXTVAL
    , 1
    , 1
    , '제목'
    , '내용'
    , '2023-12-01'
);
INSERT INTO RESIDENT_BOARD(
    BOARD_NO
    , WRITER_NO
    , CATEGORY_NO
    , TITLE
    , CONTENT
    , ENROLL_DATE
) VALUES (
    SEQ_RESIDENT_BOARD_NO.NEXTVAL
    , 1
    , 1
    , '제목'
    , '내용'
    , '2023-12-02'
);
INSERT INTO RESIDENT_BOARD(
    BOARD_NO
    , WRITER_NO
    , CATEGORY_NO
    , TITLE
    , CONTENT
    , ENROLL_DATE
) VALUES (
    SEQ_RESIDENT_BOARD_NO.NEXTVAL
    , 1
    , 1
    , '제목'
    , '내용'
    , '2023-12-03'
);

--이미지 디비화
INSERT INTO RESIDENT_BOARD_IMG(
    IMG_NO
    , BOARD_NO
    , IMG_NAME
    , PATH
    , ORIGIN_NAME
) VALUES (
    SEQ_RESIDENT_BOARD_IMG_NO.NEXTVAL
    , 1
    , '이미지01'
    , '경로01'
    , '원본명01'
);
INSERT INTO RESIDENT_BOARD_IMG(
    IMG_NO
    , BOARD_NO
    , IMG_NAME
    , PATH
    , ORIGIN_NAME
) VALUES (
    SEQ_RESIDENT_BOARD_IMG_NO.NEXTVAL
    , 1
    , '이미지02'
    , '경로01'
    , '원본명02'
);
--댓글 작성
INSERT INTO BOARD_REPLY(
    REPLY_NO
    , MEMBER_NO
    , BOARD_NO
    , CONTENT
    , ENROLL_DATE
)
VALUES (
    SEQ_BOARD_REPLY_NO.NEXTVAL
    , 1
    , 1
    , '댓글'
    , '2023-12-05'
);
INSERT INTO BOARD_REPLY(
    REPLY_NO
    , MEMBER_NO
    , BOARD_NO
    , CONTENT
    , ENROLL_DATE
)
VALUES (
    SEQ_BOARD_REPLY_NO.NEXTVAL
    , 1
    , 1
    , '댓글'
    , '2023-12-06'
);
INSERT INTO BOARD_REPLY(
    REPLY_NO
    , MEMBER_NO
    , BOARD_NO
    , CONTENT
    , ENROLL_DATE
)
VALUES (
    SEQ_BOARD_REPLY_NO.NEXTVAL
    , 1
    , 3
    , '댓글'
    , '2023-12-09'
);

INSERT INTO BOARD_REPLY(
    REPLY_NO
    , MEMBER_NO
    , BOARD_NO
    , CONTENT
    , ENROLL_DATE
)
VALUES (
    SEQ_BOARD_REPLY_NO.NEXTVAL
    , 1
    , 2
    , '댓글'
    , '2023-12-09'
);

--좋아요 추가
INSERT INTO BOARD_LIKE(
    MEMBER_NO
    , BOARD_NO
) VALUES (
    1
    , 1
);
INSERT INTO BOARD_LIKE(
    MEMBER_NO
    , BOARD_NO
) VALUES (
    2
    , 1
);
INSERT INTO BOARD_LIKE(
    MEMBER_NO
    , BOARD_NO
) VALUES (
    1
    , 2
);

-- 여기부터 덕기님

--VOTE 게시글, VOTE 항목, 
INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT, ENROLL_DATE, DEADLINE_DATE ,HIT) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'01번 테스트 전자 투표1111' ,'1111 테스트용 투표 진행합니다.','2023-12-01 15:10:07','2024-12-11 15:10:07',100 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'찬성' ,1  );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'반대' ,2 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,1 ,'중립' ,3 );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,1,'2023-12-11 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,2,'2023-12-11 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,3,'2023-12-11 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,1,4,'2023-12-11 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,5,'2023-12-11 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,6,'2023-12-11 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,7,'2023-12-11 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,8,'2023-12-11 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,2,9,'2023-12-11 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,1,3,10,'2023-12-11 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT, ENROLL_DATE, DEADLINE_DATE ,HIT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'02번 테스트 전자 투표2222' ,'2222 테스트용 투표 진행합니다.','2023-12-01 15:10:07','2024-12-11 15:10:07',120 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,2 ,'YES' ,1  );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,2 ,'NO' ,2  );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,4,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,2,5,10,'2023-12-15 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT, ENROLL_DATE, DEADLINE_DATE,HIT) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'03번 테스트 전자 투표2222' ,'3333 테스트용 투표 진행합니다.','2023-12-03 18:10:07' ,'2023-12-30 15:30:58',500);
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'보라색' ,1 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'파란색' ,2 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,3 ,'노란색' ,3 );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,6,5,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,7,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,8,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,3,8,10,'2023-12-15 15:30:07'); --걸림
INSERT INTO VOTE_HISTORY ( VOTE_HISTORY_NO ,VOTE_NO ,VOTE_NAME ,VOTE_COUNT ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_HISTORY_NO.NEXTVAL ,3 ,'파란색' ,3 ,2 );


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT, ENROLL_DATE, DEADLINE_DATE ,HIT ) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'04번 테스트 전자 투표2222' ,'4444 테스트용 투표 진행합니다.','2023-12-07 18:10:07' ,'2024-12-30 15:30:58' ,283);
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,4 ,'찬' ,1  );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,4 ,'반' ,2  );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,9,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,4,10,10,'2023-12-15 15:30:07');


INSERT INTO VOTE_BOARD ( VOTE_NO ,MANAGER_NO ,TITLE ,CONTENT, ENROLL_DATE, DEADLINE_DATE ,HIT) 
VALUES ( SEQ_VOTE_BOARD_NO.NEXTVAL ,1 ,'05번 테스트 전자 투표2222' ,'5555 테스트용 투표 진행합니다.','2023-12-01 20:10:07' ,'2024-12-30 15:30:58',684 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER  ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'김씨' ,1);
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER  ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'이씨' ,2 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER  ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'박씨' ,3  );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER  ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'정씨' ,4 );
INSERT INTO VOTE_ITEM ( ITEM_NO ,VOTE_NO ,ITEM_NAME ,VOTE_ORDER  ) 
VALUES ( SEQ_VOTE_ITEM_NO.NEXTVAL ,5 ,'조씨' ,5 );
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,11,1,'2023-12-10 15:10:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,2,'2023-12-12 15:11:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,3,'2023-12-13 15:12:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,4,'2023-12-10 15:13:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,5,'2023-12-09 15:14:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,14,6,'2023-12-08 15:15:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,7,'2023-12-04 15:16:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,13,8,'2023-12-06 15:17:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,9,'2023-12-09 15:18:07');
INSERT INTO VOTE_REPLY ( REPLY_NO ,VOTE_NO ,ITEM_NO ,PRTC_NO ,RETC_DATE ) VALUES (SEQ_VOTE_REPLY_NO.NEXTVAL,5,12,10,'2023-12-15 15:30:07');


--COMPLAINT 민원글, COMPLAINT_IMG 민원글 이미지
INSERT INTO COMPLAINT ( COMPLAINT_NO ,MEMBER_NO ,TITLE ,CONTENT ,ENROLL_DATE ) 
VALUES ( SEQ_COMPLAINT_NO.NEXTVAL,1 ,'111 테스트 민원 글 제목입니다.' ,'111 민원 테스트 본문 글입니다.','2023-12-10 15:10:07' ) ;
INSERT INTO COMPLAINT_IMG ( IMG_NO ,COMPLAINT_NO ,IMG_NAME ,PATH ,ORIGIN_NAME ) 
VALUES ( SEQ_COMPLAINT_IMG_NO.NEXTVAL ,1 ,'8cb89d95-1733-41dd-8037-8d3d6a2be6cd1705893262167.svg' ,'http://127.0.0.1:8888/app/resources/upload/complaint/img/' ,'logo.svg' ) ;

INSERT INTO COMPLAINT ( COMPLAINT_NO ,MANAGER_NO ,MEMBER_NO ,TITLE ,CONTENT ,ENROLL_DATE ) 
VALUES ( SEQ_COMPLAINT_NO.NEXTVAL ,1 ,2 ,'222 테스트 민원 글 제목입니다.' ,'222 민원 테스트 본문 글입니다.','2023-12-12 15:10:07' ) ;
INSERT INTO COMPLAINT_IMG ( IMG_NO ,COMPLAINT_NO ,IMG_NAME ,PATH ,ORIGIN_NAME ) 
VALUES ( SEQ_COMPLAINT_IMG_NO.NEXTVAL ,2 ,'2bc05527-8b12-4ebf-b54a-0d6e977374161705893167474.svg' ,'http://127.0.0.1:8888/app/resources/upload/complaint/img/' ,'logo.svg' ) ;

INSERT INTO COMPLAINT ( COMPLAINT_NO, MANAGER_NO ,MEMBER_NO ,TITLE ,CONTENT ,ENROLL_DATE, STATUS, REPLY, REPLY_DATE ) 
VALUES ( SEQ_COMPLAINT_NO.NEXTVAL, 1 ,3 ,'333 테스트 민원 글 제목입니다.' ,'333 민원 테스트 본문 글입니다.','2023-12-15 15:10:07', 'Y', '111테스트 답변 입니다.', '2023-12-19 15:10:07' ) ;
INSERT INTO COMPLAINT_IMG ( IMG_NO ,COMPLAINT_NO ,IMG_NAME ,PATH ,ORIGIN_NAME ) 
VALUES ( SEQ_COMPLAINT_IMG_NO.NEXTVAL ,3 ,'65c42d21-aef2-49df-ac28-4c1ee29db5791705891589761.svg' ,'http://127.0.0.1:8888/app/resources/upload/complaint/img/' ,'logo.svg' ) ;

INSERT INTO COMPLAINT ( COMPLAINT_NO,MANAGER_NO ,MEMBER_NO ,TITLE ,CONTENT ,ENROLL_DATE, STATUS, REPLY, REPLY_DATE ) 
VALUES ( SEQ_COMPLAINT_NO.NEXTVAL  ,1 ,4 ,'444 테스트 민원 글 제목입니다.' ,'444 민원 테스트 본문 글입니다.','2023-12-16 15:10:07', 'Y', '222테스트 답변 입니다.', '2023-12-18 15:10:07' ) ;
INSERT INTO COMPLAINT_IMG ( IMG_NO ,COMPLAINT_NO ,IMG_NAME ,PATH ,ORIGIN_NAME ) 
VALUES ( SEQ_COMPLAINT_IMG_NO.NEXTVAL ,4 ,'c392bcc3-7da3-4efd-865b-5600c71039f01705891043509.svg' ,'http://127.0.0.1:8888/app/resources/upload/complaint/img/' ,'logo.svg' ) ;

INSERT INTO COMPLAINT ( COMPLAINT_NO ,MEMBER_NO ,TITLE ,CONTENT ,ENROLL_DATE ) 
VALUES ( SEQ_COMPLAINT_NO.NEXTVAL ,5 ,'555 테스트 민원 글 제목입니다.' ,'555 민원 테스트 본문 글입니다.','2023-12-18 15:10:07' ) ;
INSERT INTO COMPLAINT_IMG ( IMG_NO ,COMPLAINT_NO ,IMG_NAME ,PATH ,ORIGIN_NAME ) 
VALUES ( SEQ_COMPLAINT_IMG_NO.NEXTVAL ,5 ,'edc99e31-e362-4808-b796-d465d9ed06501705891749649.svg' ,'http://127.0.0.1:8888/app/resources/upload/complaint/img/' ,'logo.svg' ) ;

COMMIT;




