-- DELETE TABLE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE UNIT CASCADE CONSTRAINTS;
DROP TABLE PARKING  CASCADE CONSTRAINTS;
DROP TABLE MANAGEMENT_FEE  CASCADE CONSTRAINTS;
DROP TABLE RESIDENT_BOARD   CASCADE CONSTRAINTS;
DROP TABLE RESIDENT_BOARD_IMG CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE FACILITIES_HISTORY  CASCADE CONSTRAINTS;
DROP TABLE FACILITIES  CASCADE CONSTRAINTS;
DROP TABLE FACILITIES_NOTICE CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT_IMG CASCADE CONSTRAINTS;
DROP TABLE COMPLAINT  CASCADE CONSTRAINTS;
DROP TABLE COMPLAINT_IMG CASCADE CONSTRAINTS;
DROP TABLE VOTE_REPLY CASCADE CONSTRAINTS;
DROP TABLE VOTE_BOARD CASCADE CONSTRAINTS;
DROP TABLE VOTE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE VOTE_ITEM  CASCADE CONSTRAINTS;


CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"UNIT_NO"	NUMBER		NOT NULL,
	"PHONE"	CHAR(13)		NOT NULL,
	"PWD"	VARCHAR2(50)		NOT NULL,
	"OWNER_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"BIRTH"	CHAR(6)		NOT NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PERMISSION_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."UNIT_NO" IS '세대번호';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호가 아이디';

COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."OWNER_YN" IS '세대주여부';

COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '성별';

COMMENT ON COLUMN "MEMBER"."BIRTH" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."DEL_YN" IS '이사 시 탈퇴';

COMMENT ON COLUMN "MEMBER"."PERMISSION_YN" IS '관리자의  승인절차';

CREATE TABLE "UNIT" (
	"UNIT_NO"	NUMBER		NOT NULL,
	"DONG"	NUMBER		NOT NULL,
	"HO"	NUMBER		NOT NULL,
	"SCALE"	NUMBER		NOT NULL,
	"VEH_TIME"	NUMBER	DEFAULT 6000	NOT NULL
);

COMMENT ON COLUMN "UNIT"."UNIT_NO" IS '세대번호';

COMMENT ON COLUMN "UNIT"."DONG" IS '동';

COMMENT ON COLUMN "UNIT"."HO" IS '호수';

COMMENT ON COLUMN "UNIT"."SCALE" IS '평수';

COMMENT ON COLUMN "UNIT"."VEH_TIME" IS '방문 차량 주차 시간(분)';

CREATE TABLE "RESIDENT_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"WRITER_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NULL,
	"CONTENT"	VARCHAR2(4000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL,
	"HIT"	NUMBER	DEFAULT 0	NULL
);

COMMENT ON COLUMN "RESIDENT_BOARD"."BOARD_NO" IS '게시판 번호';

COMMENT ON COLUMN "RESIDENT_BOARD"."WRITER_NO" IS '작성자 번호';

COMMENT ON COLUMN "RESIDENT_BOARD"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "RESIDENT_BOARD"."TITLE" IS '제목';

COMMENT ON COLUMN "RESIDENT_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "RESIDENT_BOARD"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "RESIDENT_BOARD"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "RESIDENT_BOARD"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "RESIDENT_BOARD"."HIT" IS '조회';

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호';

CREATE TABLE "BOARD_REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEY_YN"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_NO" IS '댓글번호';

COMMENT ON COLUMN "BOARD_REPLY"."MEMBER_NO" IS '댓글 작성자 번호';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD_REPLY"."CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "BOARD_REPLY"."ENROLL_DATE" IS '작성 일자';

COMMENT ON COLUMN "BOARD_REPLY"."MODIFY_DATE" IS '수정 일자';

COMMENT ON COLUMN "BOARD_REPLY"."DEY_YN" IS '삭제 일자';

CREATE TABLE "COMPLAINT" (
	"COMPLAINT_NO"	NUMBER		NOT NULL,
	"MANAGER_NO"	NUMBER		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(200)		NULL,
	"CONTENT"	VARCHAR2(4000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL ,
	"STATUS"	CHAR(1) DEFAULT 'N'		NULL,
	"REPLY"	VARCHAR2(4000)		NULL,
	"REPLY_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "COMPLAINT"."COMPLAINT_NO" IS '민원 번호';

COMMENT ON COLUMN "COMPLAINT"."MANAGER_NO" IS '민원 처리 담당자 관리자 번호';

COMMENT ON COLUMN "COMPLAINT"."MEMBER_NO" IS '작성자 번호';

COMMENT ON COLUMN "COMPLAINT"."TITLE" IS '민원 제목';

COMMENT ON COLUMN "COMPLAINT"."CONTENT" IS '민원 내용';

COMMENT ON COLUMN "COMPLAINT"."ENROLL_DATE" IS '작성일자';

COMMENT ON COLUMN "COMPLAINT"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "COMPLAINT"."STATUS" IS '민원처리상태';

COMMENT ON COLUMN "COMPLAINT"."REPLY" IS '민원 처리 답변';

COMMENT ON COLUMN "COMPLAINT"."REPLY_DATE" IS '민원 처리 일자';

CREATE TABLE "COMPLAINT_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"COMPLAINT_NO"	NUMBER		NOT NULL,
	"IMG_NAME"	VARCHAR2(100)		NULL,
	"PATH"	VARCHAR2(4000)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "COMPLAINT_IMG"."COMPLAINT_NO" IS '민원하자접수(외래키)';

COMMENT ON COLUMN "COMPLAINT_IMG"."IMG_NAME" IS '이미지 이름';

COMMENT ON COLUMN "COMPLAINT_IMG"."PATH" IS '이미지 경로';

COMMENT ON COLUMN "COMPLAINT_IMG"."ORIGIN_NAME" IS '이미지 원이름';

CREATE TABLE "MANAGER" (
	"MANAGER_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(100)		NOT NULL,
	"PWD"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MANAGER"."ID" IS '관리자 아이디';

COMMENT ON COLUMN "MANAGER"."PWD" IS '관리자 비밀번호';

CREATE TABLE "RESIDENT_BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"IMG_NAME"	VARCHAR2(100)		NULL,
	"PATH"	VARCHAR2(4000)		NULL,
	"ORIGIN_NAME"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "RESIDENT_BOARD_IMG"."IMG_NO" IS '이미지번호';

COMMENT ON COLUMN "RESIDENT_BOARD_IMG"."BOARD_NO" IS '게시글  번호';

COMMENT ON COLUMN "RESIDENT_BOARD_IMG"."IMG_NAME" IS '이미지 이름';

COMMENT ON COLUMN "RESIDENT_BOARD_IMG"."PATH" IS '이미지 경로';

COMMENT ON COLUMN "RESIDENT_BOARD_IMG"."ORIGIN_NAME" IS '이미지 원이름';

CREATE TABLE "VOTE_BOARD" (
	"VOTE_NO"	NUMBER		NOT NULL,
	"MANAGER_NO"	VARCHAR(255)		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NULL,
	"CONTENT"	VARCHAR2(4000)		NULL,
    "HIT"       NUMBER DEFAULT 0         NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEADLINE_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL,
	"ACCEPT_YN"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "VOTE_BOARD"."VOTE_NO" IS '투표글 번호';

COMMENT ON COLUMN "VOTE_BOARD"."MANAGER_NO" IS '작성자 번호';

COMMENT ON COLUMN "VOTE_BOARD"."TITLE" IS '글 제목';

COMMENT ON COLUMN "VOTE_BOARD"."CONTENT" IS '글 설명';

COMMENT ON COLUMN "VOTE_BOARD"."HIT" IS '조회수';

COMMENT ON COLUMN "VOTE_BOARD"."ENROLL_DATE" IS '등록 일자';

COMMENT ON COLUMN "VOTE_BOARD"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "VOTE_BOARD"."DEADLINE_DATE" IS '마감 일자';

COMMENT ON COLUMN "VOTE_BOARD"."DEL_YN" IS '삭제 여부';

COMMENT ON COLUMN "VOTE_BOARD"."ACCEPT_YN" IS '허가 여부';

CREATE TABLE "CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR(100)	DEFAULT 'ETC'	NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS '게시판 카테고리 명';

CREATE TABLE "FACILITIES_HISTORY" (
	"APPLICATION_NO"	NUMBER		NOT NULL,
	"FACILITIES_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"APPLICATION_DATE"	TIMESTAMP DEFAULT SYSDATE		NOT NULL,
	"USE_DATE"	TIMESTAMP		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"CANCEL_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "FACILITIES_HISTORY"."APPLICATION_NO" IS '신청번호';

COMMENT ON COLUMN "FACILITIES_HISTORY"."FACILITIES_NO" IS '커뮤니티 시설번호';

COMMENT ON COLUMN "FACILITIES_HISTORY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "FACILITIES_HISTORY"."APPLICATION_DATE" IS '신청 일시(결제일시)';

COMMENT ON COLUMN "FACILITIES_HISTORY"."USE_DATE" IS '이용 일시';

COMMENT ON COLUMN "FACILITIES_HISTORY"."PRICE" IS '결제금액';

COMMENT ON COLUMN "FACILITIES_HISTORY"."CANCEL_DATE" IS '신청취소일시(결제취소일시)';

CREATE TABLE "VOTE_ITEM" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"VOTE_NO"	NUMBER		NOT NULL,
	"ITEM_NAME"	VARCHAR2(1000)		NULL,
	"VOTE_ORDER"	NUMBER		NULL,
	"VOTE_TYPE"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "VOTE_ITEM"."ITEM_NO" IS '투표 항목 번호';

COMMENT ON COLUMN "VOTE_ITEM"."VOTE_NO" IS '투표글 번호';

COMMENT ON COLUMN "VOTE_ITEM"."ITEM_NAME" IS '투표 항목 명';

COMMENT ON COLUMN "VOTE_ITEM"."VOTE_ORDER" IS '표기순서';

COMMENT ON COLUMN "VOTE_ITEM"."VOTE_TYPE" IS '항목 유형';

CREATE TABLE "ANNOUNCEMENT" (
	"ANNOUNCEMENT_NO"	NUMBER		NOT NULL,
	"MANAGER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(200)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCEMENT_NO" IS '공지사항번호';

COMMENT ON COLUMN "ANNOUNCEMENT"."MANAGER_NO" IS '관리자 번호';

COMMENT ON COLUMN "ANNOUNCEMENT"."TITLE" IS '제목';

COMMENT ON COLUMN "ANNOUNCEMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "ANNOUNCEMENT"."ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "ANNOUNCEMENT"."MODIFY_DATE" IS '수정일';

COMMENT ON COLUMN "ANNOUNCEMENT"."DEL_YN" IS '삭제 여부';

CREATE TABLE "VOTE_HISTORY" (
	"VOTE_HISTORY_NO"	NUMBER		NOT NULL,
	"VOTE_NO"	NUMBER		NOT NULL,
	"VOTE_NAME"	VARCHAR2(1000)		NULL,
	"VOTE_COUNT"	NUMBER		NULL,
	"VOTE_ORDER"	NUMBER		NULL
);

COMMENT ON COLUMN "VOTE_HISTORY"."VOTE_HISTORY_NO" IS '결과 이력 번호';

COMMENT ON COLUMN "VOTE_HISTORY"."VOTE_NO" IS '투표글 번호';

COMMENT ON COLUMN "VOTE_HISTORY"."VOTE_NAME" IS '투표 결과 항목 명';

COMMENT ON COLUMN "VOTE_HISTORY"."VOTE_COUNT" IS '투표 수';

COMMENT ON COLUMN "VOTE_HISTORY"."VOTE_ORDER" IS '표기 순서';

CREATE TABLE "ANNOUNCEMENT_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"ANNOUNCEMENT_NO"	NUMBER		NOT NULL,
	"IMG_NAME"	VARCHAR2(100)		NULL,
	"PATH"	VARCHAR2(4000)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "ANNOUNCEMENT_IMG"."IMG_NO" IS '공지사항 사진 번호';

COMMENT ON COLUMN "ANNOUNCEMENT_IMG"."ANNOUNCEMENT_NO" IS '공지사항 번호(외래키)';

COMMENT ON COLUMN "ANNOUNCEMENT_IMG"."IMG_NAME" IS '이미지 이름';

COMMENT ON COLUMN "ANNOUNCEMENT_IMG"."PATH" IS '이미지 경로';

COMMENT ON COLUMN "ANNOUNCEMENT_IMG"."ORIGIN_NAME" IS '이미지 원이름';

CREATE TABLE "VOTE_REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"VOTE_NO"	NUMBER		NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL,
	"PRTC_NO"	NUMBER		NOT NULL,
	"RETC_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "VOTE_REPLY"."REPLY_NO" IS '응답번호';

COMMENT ON COLUMN "VOTE_REPLY"."VOTE_NO" IS '투표글 번호';

COMMENT ON COLUMN "VOTE_REPLY"."ITEM_NO" IS '투표 항목 번호';

COMMENT ON COLUMN "VOTE_REPLY"."PRTC_NO" IS '응답자 번호';

COMMENT ON COLUMN "VOTE_REPLY"."RETC_DATE" IS '응답일자';

CREATE TABLE "PARKING" (
	"PARKING_NO"	NUMBER		NOT NULL,
	"UNIT_NO"	NUMBER		NOT NULL,
	"PURPOSE"	VARCHAR2(1000)		NOT NULL,
	"CAR_NO"	VARCHAR2(100)		NOT NULL,
	"ARRIVAL_TIME"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DEPARTURE_TIME"	TIMESTAMP		NULL,
    "MODIFY_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "PARKING"."PARKING_NO" IS '이력번호';

COMMENT ON COLUMN "PARKING"."UNIT_NO" IS '세대번호';

COMMENT ON COLUMN "PARKING"."PURPOSE" IS '방문목적';

COMMENT ON COLUMN "PARKING"."CAR_NO" IS '차번호';

COMMENT ON COLUMN "PARKING"."ARRIVAL_TIME" IS '입차 시간';

COMMENT ON COLUMN "PARKING"."DEPARTURE_TIME" IS '출차 시간';
COMMENT ON COLUMN "PARKING"."MODIFY_DATE" IS '변경일';
COMMENT ON COLUMN "PARKING"."DEL_YN" IS '삭제여부';



CREATE TABLE "FACILITIES" (
	"FACILITIES_NO"	NUMBER		NOT NULL,
	"FACILITIES_NAME"	VARCHAR2(500)		NOT NULL,
	"UNIT_PRICE"	NUMBER		NOT NULL,
	"LOCATION"	VARCHAR2(1000)		NULL,
	"OPERATION_TIME"	VARCHAR2(1000)		NULL,
	"DAY_OFF"	VARCHAR2(1000)		NULL,
	"CONTACT"	CHAR(11)		NULL,
	"AMENITY"	VARCHAR2(1000)		NULL,
	"IMAGE"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "FACILITIES"."FACILITIES_NO" IS '커뮤니티 시설번호';

COMMENT ON COLUMN "FACILITIES"."FACILITIES_NAME" IS '커뮤니티 이름';

COMMENT ON COLUMN "FACILITIES"."UNIT_PRICE" IS '사용료';

COMMENT ON COLUMN "FACILITIES"."LOCATION" IS '시설위치';

COMMENT ON COLUMN "FACILITIES"."OPERATION_TIME" IS '운영시간';

COMMENT ON COLUMN "FACILITIES"."DAY_OFF" IS '휴일';

COMMENT ON COLUMN "FACILITIES"."CONTACT" IS '문의';

COMMENT ON COLUMN "FACILITIES"."AMENITY" IS '편의시설';

COMMENT ON COLUMN "FACILITIES"."IMAGE" IS '대표이미지';

COMMENT ON COLUMN "FACILITIES"."ENROLL_DATE" IS '등록일시';

COMMENT ON COLUMN "FACILITIES"."MODIFY_DATE" IS '마지막수정일시';

COMMENT ON COLUMN "FACILITIES"."DEL_YN" IS '삭제여부';

CREATE TABLE "MANAGEMENT_FEE" (
	"BILLING_NO"	NUMBER		NOT NULL,
	"UNIT_NO"	NUMBER		NOT NULL,
	"USAGE_PERIOD"	TIMESTAMP		NOT NULL,
	"BASIC_FEE"	NUMBER		NULL,
	"MAINTERNANCE_FEE"	NUMBER		NULL,
	"FACILITIES_FEE"	NUMBER		NULL,
	"TOTAL_AMOUNT"	NUMBER		NULL
);

COMMENT ON COLUMN "MANAGEMENT_FEE"."BILLING_NO" IS '청구번호';

COMMENT ON COLUMN "MANAGEMENT_FEE"."UNIT_NO" IS '세대번호';

COMMENT ON COLUMN "MANAGEMENT_FEE"."USAGE_PERIOD" IS '사용년월';

COMMENT ON COLUMN "MANAGEMENT_FEE"."BASIC_FEE" IS '일반관리비(청소비, 경비비같은 공동 사용료 포함임)';

COMMENT ON COLUMN "MANAGEMENT_FEE"."MAINTERNANCE_FEE" IS '세대사용료(세대전기료, 세대수도료, 세대난방비 등)';

COMMENT ON COLUMN "MANAGEMENT_FEE"."FACILITIES_FEE" IS '커뮤니티 사용료';

COMMENT ON COLUMN "MANAGEMENT_FEE"."TOTAL_AMOUNT" IS '관리비합계';

CREATE TABLE "FACILITIES_NOTICE" (
	"FACILITIES_NOTICE_NO"	NUMBER		NOT NULL,
	"FACILITIES_NO"	NUMBER		NOT NULL,
	"MANAGER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"FILE_NAME"	VARCHAR2(1000)		NULL,
	"FILE_NAME_RAW"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "FACILITIES_NOTICE"."FACILITIES_NOTICE_NO" IS '커뮤니티공지번호';

COMMENT ON COLUMN "FACILITIES_NOTICE"."FACILITIES_NO" IS '커뮤니티 시설번호';

COMMENT ON COLUMN "FACILITIES_NOTICE"."MANAGER_NO" IS '관리자 번호';

COMMENT ON COLUMN "FACILITIES_NOTICE"."TITLE" IS '제목';

COMMENT ON COLUMN "FACILITIES_NOTICE"."CONTENT" IS '내용';

COMMENT ON COLUMN "FACILITIES_NOTICE"."ENROLL_DATE" IS '작성일시';

COMMENT ON COLUMN "FACILITIES_NOTICE"."MODIFY_DATE" IS '수정일시';

COMMENT ON COLUMN "FACILITIES_NOTICE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "FACILITIES_NOTICE"."FILE_NAME" IS '첨부파일';

COMMENT ON COLUMN "FACILITIES_NOTICE"."FILE_NAME_RAW" IS '원 첨부파일명';



ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "UNIT" ADD CONSTRAINT "PK_UNIT" PRIMARY KEY (
	"UNIT_NO"
);

ALTER TABLE "RESIDENT_BOARD" ADD CONSTRAINT "PK_RESIDENT_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "PK_BOARD_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "COMPLAINT" ADD CONSTRAINT "PK_COMPLAINT" PRIMARY KEY (
	"COMPLAINT_NO"
);

ALTER TABLE "COMPLAINT_IMG" ADD CONSTRAINT "PK_COMPLAINT_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "MANAGER" ADD CONSTRAINT "PK_MANAGER" PRIMARY KEY (
	"MANAGER_NO"
);

ALTER TABLE "RESIDENT_BOARD_IMG" ADD CONSTRAINT "PK_RESIDENT_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "VOTE_BOARD" ADD CONSTRAINT "PK_VOTE_BOARD" PRIMARY KEY (
	"VOTE_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "FACILITIES_HISTORY" ADD CONSTRAINT "PK_FACILITIES_HISTORY" PRIMARY KEY (
	"APPLICATION_NO"
);

ALTER TABLE "VOTE_ITEM" ADD CONSTRAINT "PK_VOTE_ITEM" PRIMARY KEY (
	"ITEM_NO"
);

ALTER TABLE "ANNOUNCEMENT" ADD CONSTRAINT "PK_ANNOUNCEMENT" PRIMARY KEY (
	"ANNOUNCEMENT_NO"
);

ALTER TABLE "VOTE_HISTORY" ADD CONSTRAINT "PK_VOTE_HISTORY" PRIMARY KEY (
	"VOTE_HISTORY_NO"
);

ALTER TABLE "ANNOUNCEMENT_IMG" ADD CONSTRAINT "PK_ANNOUNCEMENT_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "VOTE_REPLY" ADD CONSTRAINT "PK_VOTE_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "PARKING" ADD CONSTRAINT "PK_PARKING" PRIMARY KEY (
	"PARKING_NO"
);



ALTER TABLE "FACILITIES" ADD CONSTRAINT "PK_FACILITIES" PRIMARY KEY (
	"FACILITIES_NO"
);

ALTER TABLE "MANAGEMENT_FEE" ADD CONSTRAINT "PK_MANAGEMENT_FEE" PRIMARY KEY (
	"BILLING_NO"
);

ALTER TABLE "FACILITIES_NOTICE" ADD CONSTRAINT "PK_FACILITIES_NOTICE" PRIMARY KEY (
	"FACILITIES_NOTICE_NO"
);

------- 시퀀스 --------
DROP SEQUENCE SEQ_MEMBER_NO ;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_UNIT_NO ;
CREATE SEQUENCE SEQ_UNIT_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_PARKING_NO ;
CREATE SEQUENCE SEQ_PARKING_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_MANAGEMENT_FEE_NO ;
CREATE SEQUENCE SEQ_MANAGEMENT_FEE_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_BOARD_REPLY_NO ;
CREATE SEQUENCE SEQ_BOARD_REPLY_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_RESIDENT_BOARD_NO ;
CREATE SEQUENCE SEQ_RESIDENT_BOARD_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_CATEGORY_NO ;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_RESIDENT_BOARD_IMG_NO ;
CREATE SEQUENCE SEQ_RESIDENT_BOARD_IMG_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_FACILITIES_HISTORY_NO ;
CREATE SEQUENCE SEQ_FACILITIES_HISTORY_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_FACILITIES_NO ;
CREATE SEQUENCE SEQ_FACILITIES_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_FACILITIES_NOTICE ;
CREATE SEQUENCE SEQ_FACILITIES_NOTICE NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_COMPLAINT_NO ;
CREATE SEQUENCE SEQ_COMPLAINT_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_COMPLAINT_IMG_NO ;
CREATE SEQUENCE SEQ_COMPLAINT_IMG_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_MANAGER_NO ;
CREATE SEQUENCE SEQ_MANAGER_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_ANNOUNCEMENT_NO ;
CREATE SEQUENCE SEQ_ANNOUNCEMENT_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_ANNOUNCEMENT_IMG_NO ;
CREATE SEQUENCE SEQ_ANNOUNCEMENT_IMG_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_VOTE_REPLY_NO ;
CREATE SEQUENCE SEQ_VOTE_REPLY_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_VOTE_BOARD_NO ;
CREATE SEQUENCE SEQ_VOTE_BOARD_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_VOTE_HISTORY_NO ;
CREATE SEQUENCE SEQ_VOTE_HISTORY_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_VOTE_ITEM_NO ;
CREATE SEQUENCE SEQ_VOTE_ITEM_NO NOCACHE NOCYCLE;

